### ISSUE TITLE
User's follow list does not persist

### ISSUE THREAD

**Issue by unepipe** [p4sh4/oi#1]
The follow list does not persist (when you close app and reopen it, the user loses the list of people they follow)

**Comment by p4sh4** [comment]
Does it happen every time? It seems to be fine for me. The list isn't saved to the device, it's populated from the Parse backend, and does it on login or opening the friend list. Do you have internet connection when you close the app and reopen it?

**Comment by keepnone** [comment]
Yea I have the same problem as well, and I'm always connected to the internet.

**Comment by swbam** [comment]
Can the issue of the friends list not saving get fixed?
